# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=1080)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('type', models.CharField(choices=[('CL', 'College'), ('LI', 'Library'), ('IN', 'Industry'), ('HO', 'Hotel'), ('ZO', 'Zoo'), ('MU', 'Musuem'), ('RE', 'Restaurant'), ('MA', 'Mall')], max_length=2)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.City')),
            ],
        ),
    ]
