# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('ticket_link', models.CharField(max_length=14, unique=True)),
                ('type', models.CharField(choices=[('LM', 'Live Music'), ('SP', 'Sports')], max_length=2)),
                ('description', models.CharField(max_length=1080)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.City')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Tourist', 'Tourist'), ('Businessman', 'Businessman')], max_length=30),
        ),
    ]
