# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0008_profile_temporary_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='temporary_access',
        ),
    ]
