# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0010_auto_20171031_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_link',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Live Music', 'Live Music'), ('Sports', 'Sports')], max_length=128),
        ),
    ]
