# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0011_auto_20171031_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='departments',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
