# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0012_location_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='departments',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
